{% set name = "bigearthnet-gdf-builder" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bigearthnet_gdf_builder-{{ version }}.tar.gz
  sha256: 66f8f8549717924f514fa3c96cf16412765407e35b8db667665e32f9b82c1b75

build:
  entry_points:
    - ben_gdf_builder = bigearthnet_gdf_builder.builder:_run_gdf_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - appdirs >=1.4,<2.0
    - bigearthnet-common >=2.4,<=3.0
    - fastcore >=1.3,<2.0
    - geopandas >=0.10,<0.12
    - natsort >=8,<9
    - pyarrow >=6,<7
    - pydantic >=1.8,<2.0
    - pygeos >=0.12,<0.13
    - python >={{ python_min }},<4.0
    - rich >=10
    - typer >=0.4,<0.5

test:
  imports:
    - bigearthnet_gdf_builder
  commands:
    - pip check
    - ben_gdf_builder --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kai-tub/bigearthnet_gdf_builder/
  summary: A package to generate and extend BigEarthNet GeoDataFrames.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
